baseURL: ""
languageCode: "en-us"
theme: "hugo-bootstrap-bare"
author: 
  name: "Kristian Köhntopp"
  twitter: "isotopp"

title: "Die wunderbare Welt von Isotopp"
description: "Something old, something new, something borrowed, something blue"

frontmatter:
  date: [":filename", ":default"]

paginate: 20
paginatePath: blog

permalinks:
  posts: /:year/:month/:day/:slug/

UglyURLS: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: "About"
      url: "/about/"
    - identifier: contribute
      name: "Contribute"
      url: "/contribute/"


taxonomies:
  tag: tags

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    noClasses: false
    style: nord
    #style: monokai
