baseURL: "https://blog.koehntopp.info"
languageCode: "en-us"
theme: "hugo-bootstrap-bare"
author: 
  name: "Kristian Köhntopp"
  twitter: "isotopp"

title: "Die wunderbare Welt von Isotopp"
description: "Something old, something new, something borrowed, something blue"

frontmatter:
  date: [":filename", ":default"]

paginate: 20
paginatePath: blog
enableEmoji: true
permalinks:
  posts: /:year/:month/:day/:slug/

UglyURLS: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: contribute
      name: "Contribute"
      url: "/contribute/"
      weight: 2
    - identifier: search
      pre: "<svg class='bi' height='1.5rem' width='1.5rem' fill='currentColor'><use xlink:href='/bootstrap-icons.svg#search'/></svg>"
      url: "/search/"
      weight: 3
    - identifier: tags
      pre: "<svg class='bi' width='1.5rem' height='1.5rem' fill='currentColor'><use xlink:href='/bootstrap-icons.svg#tags-fill'/></svg>"
      name: ""
      url: "/tags/"
      weight: 0


taxonomies:
  tag: tags

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    noClasses: false
    style: pygment
    #style: nord
    #style: monokai

